apiVersion: apps/v1
kind: Deployment
metadata:
  name: projeto1
  labels:
    app: projeto1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projeto1
  template:
    metadata:
      labels:
        app: projeto1
    spec:
      containers:
      - name: projeto1
        image: docker.io/lasher/debugocp
        ports:
        - containerPort: 8080
