apiVersion: v1
kind: Service
metadata:
  name: projeto1
  labels:
    app: projeto1
spec:
  selector:
    app: projeto1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
