apiVersion: apps/v1
kind: Deployment
metadata:
  name: projeto2
  labels:
    app: projeto2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projeto2
  template:
    metadata:
      labels:
        app: projeto2
    spec:
      containers:
      - name: projeto2
        image: docker.io/lasher/debugocp
        ports:
        - containerPort: 8080
