apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-demo2
  labels:
    app: app-demo2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-demo2
  template:
    metadata:
      labels:
        app: app-demo2
    spec:
      containers:
      - name: app-demo2
        image: docker.io/lasher/debugocp
        ports:
        - containerPort: 8080
