apiVersion: v1
kind: Service
metadata:
  name: app-demo2
  labels:
    app: app-demo2
spec:
  selector:
    app: app-demo2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
