apiVersion: v1
kind: Service
metadata:
  name: projeto2
  labels:
    app: projeto2
spec:
  selector:
    app: projeto2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
